# Visualisierung Klassenbenotung
## To-do
* Visualisierung Schularbeiten
* Visualisierung Wiederholungen
* Visualisierung Gesamtnote

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [11]:
data = pd.read_excel('./Excel-Vorlagen/Vorlage_Benotung_TAG.xlsx')

In [12]:
data.head(3)

,Unnamed: 0,1EK - Notenstand,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,NaN,NaN,NaN,NaN,m/w,NaN,NaN,NaN,REPASOS (20%),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Klasse,Nr.,Nachname,Vorname,Geschlecht,Wintersemester,Sommersemester,NaN,Punkte,Summe,...,Frühwarnung,Notenstand (09.05.2024),Mitarbeit,Notwendige Leistung,SA,B-Note,Jahresnote,Prüfung (24.05.2024),Eingetragen,Notentendenz
2,HAK,1,Nachname 1,Vorname 1,w,2023/24,2024,0.590369,49.5,86,...,JA,Nicht genügend,aktiver im Sommersemester,"gutes repaso; gute (~) oder (+), nicht am (-);...",Nicht genügend,4,4,NaN,2024-06-11 00:00:00,NaN

In [13]:

# Set the appropriate row as the header and drop the rows above
data.columns = data.iloc[1]  # Row 3 becomes the header (index 2)
data = data.drop([0,1])  # Drop rows above the new header

# Reset the index
data = data.reset_index(drop=True)

# Display the cleaned DataFrame
data

1,Klasse,Nr.,Nachname,Vorname,Geschlecht,Wintersemester,Sommersemester,NaN,Punkte,Summe,...,Frühwarnung,Notenstand (09.05.2024),Mitarbeit,Notwendige Leistung,SA,B-Note,Jahresnote,Prüfung (24.05.2024),Eingetragen,Notentendenz
0,HAK,1,Nachname 1,Vorname 1,w,2023/24,2024,0.590369,49.5,86,...,JA,Nicht genügend,aktiver im Sommersemester,"gutes repaso; gute (~) oder (+), nicht am (-);...",Nicht genügend,4,4,NaN,2024-06-11 00:00:00,NaN
1,HAK,2,Nachname 2,Vorname 2,m,2023/24,2024,0.883463,76.5,86,...,NaN,Sehr gut - Gut,"aktiv, positive Beiträge",positives repaso,Gut,1,1,NaN,2024-06-11 00:00:00,NaN
2,HAK,3,Nachname 3,Vorname 3,w,2023/24,2024,0.655926,50,86,...,NaN,Befriedigend - Genügend,aktiver im Sommersemester,"gutes repaso; gute (~) oder (+), nicht am (-)",Genügend,4,4,NaN,2024-06-11 00:00:00,NaN
3,HAK,4,Nachname 4,Vorname 4,w,2023/24,2024,0.664408,47.75,74,...,NaN,Genügend,teilweise aktiv,positives repaso,Genügend,4,4,NaN,2024-06-11 00:00:00,NaN
4,HAK,5,Nachname 5,Vorname 5,w,2023/24,2024,0.880391,80.5,86,...,NaN,Sehr gut,"aktiv, positive Beiträge, eher ruhig",positives repaso,Sehr gut,1,1,NaN,2024-06-11 00:00:00,NaN
5,HAK,6,Nachname 6,Vorname 6,w,2023/24,2024,0.721042,56.5,86,...,NaN,Gut - Befriedigend,"teilweise aktiv, eher ruhig","gutes repaso; gute (~) oder (+), nicht am (-)",Befriedigend,2,2,NaN,2024-06-11 00:00:00,NaN
6,HAK,7,Nachname 7,Vorname 7,w,2023/24,2024,0.970543,80.5,86,...,NaN,Sehr gut - Gut,"aktiv, positive Beiträge",positives repaso,Gut,1,1,NaN,2024-06-11 00:00:00,NaN

In [16]:
data.columns

Index([                         'Klasse',                             'Nr.',
                              'Nachname',                         'Vorname',
                            'Geschlecht',                  'Wintersemester',
                        'Sommersemester',                               nan,
                                'Punkte',                           'Summe',
                               'Prozent',                       'FUNKTION!',
                                'Punkte',                           'Summe',
                               'Prozent',                      'Zusatzinfo',
                                  'Note',                               nan,
                             'abgegeben',                       'verspätet',
                         'fehlt, falsch',                           'SUMME',
                                     nan,                               nan,
                                     nan,                           '( + )',
                                 '( ~ )',                           '( - )',
                           'Abwesenheit',                 'Bewertung (0-1)',
                                     nan,                               nan,
       'Verbale Beurteilung (Mitarbeit)',               2023-12-14 00:00:00,
                   'Notwendige Leistung',                              'SA',
                                'B-Note',                    'Semesternote',
                        'Eingetragen am',                               nan,
                               'SA - SS',                     'Frühwarnung',
               'Notenstand (09.05.2024)',                       'Mitarbeit',
                   'Notwendige Leistung',                              'SA',
                                'B-Note',                      'Jahresnote',
                  'Prüfung (24.05.2024)',                     'Eingetragen',
                          'Notentendenz'],
      dtype='object', name=1)

### Notwendige Änderungen:
* alle Spalten passend benennen